### PR TITLE
Add manifest and ideas documents

### PR DESCRIPTION
**Pull request by enribd**
This is a first approach to manifest declaration based on the meeting we had today, feel free to suggest changes, formatting, categorization, reordering, or even commit changes.

Also I added a file with the ideas we had in the Google Doc so we can forget about that document and work here, like real engineers :yum: 

Enjoy.

### CODE REVIEW

**Comment by christiangonre** [comment]
**FYI:** I renamed this repo as .github because is the reserved word that Github uses to their "main" repository as you can see in this documentation: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file
This repo now is public so we must be careful with the data that we commit here.

**Review by christiangonre — APPROVED** [review]
LGTM!

**Comment by mmorejon** [comment]
LGTM!

**Comment by mmorejon** [comment]
> **FYI:** I renamed this repo as .github because is the reserved word that Github uses to their "main" repository as you can see in this documentation: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file This repo now is public so we must be careful with the data that we commit here.

I think we need both repositories, `main` and `.github`. `.github` will avoid us copy/paste common files throughout all repositories otherwise, the `main` repository will be used to contain general documents like index, objectives, etc.

**Comment by enribd** [comment]
> > **FYI:** I renamed this repo as .github because is the reserved word that Github uses to their "main" repository as you can see in this documentation: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file This repo now is public so we must be careful with the data that we commit here.
> 
> I think we need both repositories, `main` and `.github`. `.github` will avoid us copy/paste common files throughout all repositories, on the other hand, the `main` repository will be used to contain general documents like index, objectives, etc.

If we keep this repo for templates and common files for repositories we need to move this files to the "index" repo, which must be created first.

**Comment by christiangonre** [comment]
> > > **FYI:** I renamed this repo as .github because is the reserved word that Github uses to their "main" repository as you can see in this documentation: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file This repo now is public so we must be careful with the data that we commit here.
> > 
> > I think we need both repositories, `main` and `.github`. `.github` will avoid us copy/paste common files throughout all repositories, on the other hand, the `main` repository will be used to contain general documents like index, objectives, etc.
> 
> If we keep this repo for templates and common files for repositories we need to move this files to the "index" repo, which must be created first. 

If we want to use the files used in this PR as presentation of the Github team, its mandatory to use this repo (.github)

**Comment by mmorejon** [comment]
> If we want to use the files used in this PR as presentation of the Github team, its mandatory to use this repo (.github)

Got it, let's start as simple as possible using the organization's profile (`/profile/README.md`) to manage these manifests. We'll have time to create a second repository if we need it.

**Review by mmorejon — APPROVED** [review]

**Pull request merged**
